# Generated by Django 4.1.7 on 2023-03-09 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('RAW', 'RAW'), ('FULLHD', 'FULLHD')], default='RAW', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('date_published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='phim.category')),
                ('videos', models.ManyToManyField(to='phim.video')),
            ],
            options={
                'ordering': ('-date_published',),
                'unique_together': {('title',)},
            },
        ),
    ]
