# Generated by Django 4.1.7 on 2023-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0004_remove_movie_videos_movie_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='videos',
        ),
        migrations.AddField(
            model_name='movie',
            name='movies',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
