# Generated by Django 4.1.7 on 2023-03-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0005_remove_movie_videos_movie_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='phim.category'),
        ),
    ]
