# Generated by Django 4.1.7 on 2023-03-10 12:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0006_delete_video_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RAW', 'RAW'), ('FULLHD', 'FULLHD'), ('COMINGSOON', 'COMINGSOON')], default='RAW', max_length=10),
        ),
    ]
