# Generated by Django 4.1.7 on 2023-03-10 12:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0007_alter_movie_flyer_alter_movie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('MALE', 'Nam'), ('FAMELE', 'Nữ'), ('LGBT', 'LGBT')], default='', max_length=10)),
                ('info', models.TextField()),
                ('birth', models.DateField()),
                ('flyer', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Fyler')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moives', to='phim.movie')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actores',
                'unique_together': {('name',)},
            },
        ),
    ]
