# Generated by Django 4.1.7 on 2023-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0008_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='contry',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
