# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0009_movie_contry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('LGBT', 'LGBT')], default='', max_length=10),
        ),
    ]
