# Generated by Django 4.1.7 on 2023-03-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0010_alter_actor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='DN',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
