# Generated by Django 4.1.7 on 2023-03-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0011_movie_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
