# Generated by Django 4.1.7 on 2023-03-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0012_movie_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(related_name='movies', to='phim.actor'),
        ),
    ]
