# Generated by Django 4.1.7 on 2023-03-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0013_remove_actor_movies_movie_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
