# Generated by Django 4.1.7 on 2023-03-11 10:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0014_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
        ),
    ]
