# Generated by Django 4.1.7 on 2023-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0016_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
