# Generated by Django 4.1.7 on 2023-03-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0017_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='DN',
            new_name='year',
        ),
    ]
