# Generated by Django 4.1.7 on 2023-03-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0018_rename_dn_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
