# Generated by Django 4.1.7 on 2023-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phim', '0021_movie_title_el'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='contry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RAW', 'RAW'), ('FULLHD', 'FULLHD'), ('COMINGSOON', 'COMINGSOON')], default='FULLHD', max_length=10),
        ),
    ]
